# Generated by Django 4.2.4 on 2023-11-27 14:12

import InventoryTooling.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLocation',
            fields=[
                ('no_loc', InventoryTooling.models.UpperChar(max_length=20, primary_key=True, serialize=False)),
                ('assign', models.CharField(max_length=1, null=True)),
                ('storage', InventoryTooling.models.UpperChar(max_length=2, null=True)),
                ('area', InventoryTooling.models.UpperChar(max_length=2, null=True)),
                ('status', models.CharField(default='FL', max_length=2, null=True)),
                ('sto_check', models.CharField(max_length=3, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_Location',
            },
        ),
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('prod_code', InventoryTooling.models.UpperChar(max_length=20, primary_key=True, serialize=False)),
                ('prod_desc', InventoryTooling.models.UpperChar(max_length=60, null=True)),
                ('pack_size', models.IntegerField(null=True)),
                ('supplier', InventoryTooling.models.UpperChar(max_length=60, null=True)),
                ('stock_min', models.IntegerField(null=True)),
                ('stock_max', models.IntegerField(null=True)),
                ('l_time_days', models.IntegerField(null=True)),
                ('status', InventoryTooling.models.UpperChar(default='ACTIVE', max_length=60, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_Product',
            },
        ),
        migrations.CreateModel(
            name='ModelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.IntegerField(null=True)),
                ('no_card', models.IntegerField(null=True)),
                ('nm_krywn', InventoryTooling.models.UpperChar(max_length=20, null=True)),
                ('dept', InventoryTooling.models.UpperChar(max_length=10, null=True)),
                ('usernm', InventoryTooling.models.LowerChar(max_length=10, null=True)),
                ('passwd', models.CharField(max_length=10, null=True)),
                ('level', InventoryTooling.models.UpperChar(max_length=3, null=True)),
            ],
            options={
                'db_table': 'tb_User',
            },
        ),
        migrations.CreateModel(
            name='ModelTransaction',
            fields=[
                ('id', models.CharField(default=InventoryTooling.models.random_id, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('no_ttb', models.CharField(max_length=10, null=True)),
                ('ttb_stat', models.CharField(max_length=2, null=True)),
                ('ttb_qty', models.IntegerField(null=True)),
                ('no_loc', InventoryTooling.models.UpperChar(max_length=20, null=True)),
                ('trans_type', models.CharField(max_length=3, null=True)),
                ('adj_type', models.CharField(max_length=2, null=True)),
                ('qty_bfr', models.IntegerField(null=True)),
                ('qty_adj', models.IntegerField(null=True)),
                ('qty_afr', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=160, null=True)),
                ('prod_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryTooling.modelproduct')),
                ('usernm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryTooling.modeluser')),
            ],
            options={
                'db_table': 'tb_Transaction',
            },
        ),
        migrations.CreateModel(
            name='ModelTempProdLoc',
            fields=[
                ('id', models.CharField(default=InventoryTooling.models.random_id, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('remark', InventoryTooling.models.UpperChar(max_length=3, null=True)),
                ('qty', models.IntegerField(default=0, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('no_loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryTooling.modellocation')),
                ('prod_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryTooling.modelproduct')),
            ],
            options={
                'db_table': 'tb_TempProdLoc',
            },
        ),
    ]
