# Generated by Django 4.2.4 on 2023-11-30 13:59

import InventoryTooling.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTooling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltransaction',
            name='usernm',
        ),
        migrations.AddField(
            model_name='modeltransaction',
            name='usrname',
            field=InventoryTooling.models.LowerChar(max_length=10, null=True),
        ),
    ]
