# Generated by Django 4.2.4 on 2023-11-30 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTooling', '0002_remove_modeltransaction_usernm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeluser',
            name='joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
