# Generated by Django 4.2.4 on 2023-12-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTooling', '0003_modeluser_joined'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelUser',
            new_name='ModelUserUID',
        ),
        migrations.AlterModelTable(
            name='modeluseruid',
            table='tb_UserUID',
        ),
    ]
