# Generated by Django 4.2.4 on 2023-12-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTooling', '0004_rename_modeluser_modeluseruid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeluseruid',
            old_name='no_card',
            new_name='uid',
        ),
    ]
