# Generated by Django 4.2.4 on 2023-12-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTooling', '0005_rename_no_card_modeluseruid_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeluseruid',
            name='passwd',
        ),
    ]
