# Generated by Django 4.2.4 on 2023-12-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryTooling', '0006_remove_modeluseruid_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeluseruid',
            name='status',
            field=models.BooleanField(default=1, null=True),
        ),
    ]
